### ISSUE TITLE
Adicione um readme personalizado

### ISSUE THREAD

**Issue by RodrigoNet0** [secultce/theme-Ceara#87]
Olá, gostaria de sugerir algo, adicionar um readme personalizado, para melhor compreensão do código. 
- ### Tópicos
- Como rodar o projeto
- Prévia, com imagens da página
- Instalação de dependências 
- Entre outros
Sugiro usar o [readme.so](https://readme.so/pt) para realização desta task.

**Comment by Junior-Shyko** [comment]
Ola @RodrigoNet0 , é muito válido a sua sugestão e vou adicionar melhoras no readme para deixar mais claro que esse é um repositório de um tema de uso de uma plataforma Open Source chamado Mapas Culturais e através da [documentação](https://github.com/mapasculturais/mapasculturais/tree/develop/documentation) deles.

Sugiro entrar no repositório deles e entender como se usa ou cria os temas da aplicação, caso você tenha alguma curiosidade ou mesmo queira contribuir, pois sempre será bem vindo.
