### ISSUE TITLE
Remover click de apagar inscrição

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/theme-Ceara#97]
## **Contexto**

- Atualmente existe um botão que foi adicionar no tema Ceará para exclusão de inscrições e essa é uma ação muito crítica pelo fato que existe em outros pontos da aplicação uma dependência de dados e acontece de algo excluir uma inscrição todo o relacionamento com essa inscrição se quebra.

## **Objetivo**

**Como** uma pessoa desenvolvedora
**Quero** remover da página o botão de **APAGAR** INSCRIÇÃO
**Para** não tem um risco crítico de bug na plataforma.

## **Escopo**

- [x] Remover botão no frontend
- [x] Bloquear rota no backend

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [x] Remover botão de **APAGAR** inscrição  
**Dado que** um administrador da oportunidade do mapa cultural
**Quando** acessar a página de inscrição
**Então** não vejo mais a coluna de ADMINISTRADOR onde tem um botão de **apagar** inscrição

# Observações
![image](https://github.com/secultce/mapasculturais-v5/assets/7341117/d0af95d7-e157-48c1-80d6-e4f5b681ac60)

**Comment by ronnyjohnti** [comment]
Remover th da tabela:

![Image](https://github.com/secultce/theme-Ceara/assets/42920699/aaebf675-cff0-43d4-8817-8e97527b3e14)

**Comment by Yasminemaciel02** [comment]
Mesmo com o perfil SuperSassAdm, o botão de apagar inscritos não consta mais.
