### ISSUE TITLE
Remover a opção de criar uma oportunidade de prestação de contas

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/theme-Ceara#98]
## **Contexto**

- Atualmente no mapa cultural existe uma fase de prestação de contas que não tem utilidade e a mesma nunca foi testada e validade, por isso não faz sentido essa opção permanecer na criação de uma nova fase.

## **Objetivo**

**Como** uma pessoa desenvolvedora do mapa cultural
**Quero** remover a opção PRESTAÇÃO DE CONTAS
**Para** não haver erros por parte do usuário

## **Critérios de Aceitação**

- [x] Remover opção de prestação de conta  
**Dado que** uma pessoa gestora de uma oportunidade
**Quando** eu clicar em criar um fase
**então** não será mostrado para mim a opção de prestação de contas

## **Escopo**

- [x] escopo1

## **Fora de Escopo**

- fora_de_escopo

# Observações
![image](https://github.com/secultce/theme-Ceara/assets/7341117/3c872649-084a-485c-bba5-4a5ca570a2f0)

**Comment by Yasminemaciel02** [comment]
Opção removida.
![image](https://github.com/user-attachments/assets/68c4fc49-4db1-4a80-8717-21567f510aba)
